### ISSUE TITLE
Tab limitations isn't respected across editor panes

### ISSUE THREAD

**Issue by willbonney** [hitode909/vscode-zentabs#1]
Thank you for making this extension, it was sorely missed from the Atom days.

When using a split layout, the tab limit is applied to all panes at once, for example opening a new tab in pane B will close tabs in pane A if the number of tabs in both panes (A + B) is exceeded.

Would it be possible for each pane to be independent and enforce the limit per pane rather than per VS Code window?

**Comment by hitode909** [comment]
@wba0 Thank you for reporting the first issue.Though I didn't split panes so much, I understood your use case.
I implemented `zentabs.applyLimitFor` option. Please set it to `editorGroup`.

```json
    "zentabs.applyLimitFor": "editorGroup"
```

You can use version 0.0.3. Thank you.

https://marketplace.visualstudio.com/items?itemName=hitode909.zentabs
