### ISSUE TITLE
Switch new file with the current selected tab instead of the oldest one.

### ISSUE THREAD

**Issue by sergiop** [hitode909/vscode-zentabs#4]
Hi @hitode909,
I like so much your work and your plugin is currently the only solution that allow me to limit opened tabs in vscode. I opened this discussion only to speak with you about the the current development status and future evolutions.

One example: currently, if you open a new file with the maximum limit reached, the oldest tab will be closed in favour of the new one. I don't like it, because I can't immediately understand which is the file that's closing, because my eyes (and my attention) are on the selected tab, not on the oldest. So, it would be nice if the user can choose to switch the new file with the current selected tab instead of the oldest tab. I think in this way I can have more control on what it's happening.

What do you think?

Best,

Sergio

**Comment by hitode909** [comment]
@sergiop Hi! Thank you for your feedback. 

> the current development status and future evolutions.

I'm using this extension everyday in my work.

> witch the new file with the current selected tab instead of the oldest tab

I think it's possible to implement this feature, but I can't imagine whether it is useful. Old tabs will remain for long time, and I'll forget why that old tab is remaining.

**Comment by sergiop** [comment]
My typical configuration is split my view in 4 grid panes, allowing a maximum of two tab per pane. In this way I can have the maximum control on which files I have opened. I mean... I don't need to open more than 8 files at the same time, and more than this... my brain starts to go in confusion.
So, my purpose is not to have "old tabs" and I exactly need to know which tab it's closing in favour of the new file I'm opening. When I'm opening a new file, my focus is on the opened tab, not on the other one. That's why closing the unselected tab it's not a behaviour I like.

Moreover, closing the oldest one, shifts the position of the other tabs, and I completely lost my focus on WHAT is opened and WHERE is opened. :-(

**Comment by sergiop** [comment]
Hi @hitode909, I just created a PR where I implemented my idea. I don't know if it's in scope with your idea of the project, also because I never used ZenTabs for Atom or Sublime, but it's what I need. ;-)

Feel free to ignore it, don't worry 🙏
Bye.

**Comment by hitode909** [comment]
@sergiop I merged your PR and released the new version. thank you!
- https://marketplace.visualstudio.com/items?itemName=hitode909.zentabs
